#!/usr/bin/python
#
# Copyright 2012 Jonathan Anderson
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


import re
import sys

from references import commasep

# This is what Papers inserts into a Lyx file.
pattern = """\\\\backslash
cite{(.*)}"""

# This is how Lyx likes to spell citations.
replacement = """\\\\begin_inset CommandInset citation
LatexCommand cite
key "\\1"

\end_inset
"""

if __name__ == '__main__':
	for arg in sys.argv[1:]:
		print arg
		f = file(arg, 'r')
		orig = f.read()
		f.close()

		modified = re.sub(pattern, replacement, orig)

		f = file(arg, 'w+')
		f.write(modified)
		f.close()

